---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres/stateful-set.yaml
  - postgres/service.yaml
  - moodle/volume-claim.yaml
  - moodle/deployment.yaml
  - moodle/service.yaml
  - redis/stateful-set.yaml
  - redis/service.yaml