apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
    role: moodle
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
spec:
  type: NodePort
  selector:
    app: moodle
    tier: frontend
    role: moodle
  ports:
    - port: 80
      targetPort: http
      nodePort: 30001
      protocol: TCP
