apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"
