
apiVersion: v1
kind: Service
metadata:
  name: moodle-redis
  labels:
    app: moodle
    role: redis
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '6379'
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: moodle
    role: redis
    tier: backend
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
